services:
  - type: web
    name: swa-project
    env: node
    buildCommand: npm install && cd client && npm ci && cd .. && npm run build -- -c=production
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_MOCK_API
        value: true
      - key: PORT
        value: 10000
